[package]
name = "termu"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tascord/termu"
description = "Terminal Emulator for Rust (*Nix Only)"

[dependencies]
nix = { version = "0.29.0", features = ["term", "fs", "process"] }
